language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - travis_wait 120 coverage run unittest_tests.py -v

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
